boatload/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponseRedirect

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'boatload.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', lambda r: HttpResponseRedirect('conductor/')),
    url(r'^conductor/', include('conductor.urls', namespace='conductor')),
    url(r'^admin/', include(admin.site.urls)),
)

conductor/urls.py
__author__ = 'keyz'
from django.conf.urls import patterns, url

from conductor import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^/result$', views.results, name='results'),
)

conductor/models.py
from django.db import models

# Create your models here.

conductor/views.py
from django.shortcuts import render
from conductor.templater import Builder
from simplejson import loads, dumps

def index(request):
    if request.method == 'POST':
        template = loads(request.POST.get("template",""))

        builder = Builder(template)
        service = builder.render_service_files()

        return render(request, 'conductor/index.html',
                      {
                          'service':service,
                          'template':dumps(template, sort_keys=True, indent=4 * ' ')
                      })
    else:
        return render(request, 'conductor/index.html')


def results(request):
    return render(request, 'conductor/results.html')

templates/conductor/index.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}

{% load staticfiles %}

{% block bootstrap3_extra_head %}
<link href="{% static "conductor/index.css" %}" rel="stylesheet">
{% endblock %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">BoatLoad</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Dashboard</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">Help</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Reports</a></li>
                <li><a href="#">Analytics</a></li>
                <li><a href="#">Export</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li><a href="">Nav item</a></li>
                <li><a href="">Nav item again</a></li>
                <li><a href="">One more nav</a></li>
                <li><a href="">Another nav item</a></li>
                <li><a href="">More navigation</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li><a href="">Nav item again</a></li>
                <li><a href="">One more nav</a></li>
                <li><a href="">Another nav item</a></li>
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">BoatLoad</h1>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="{% url 'conductor:index' %}" method="post" class="form">
                        <div class="form-group">
                            {% csrf_token %}
                            <label for="template">Template</label><br />
                            <textarea rows="25" class="form-control"  name="template" id="template" value="">{{ template }}</textarea>
                            <input type="submit" value="Submit" />
                        </div>
                    </form>
                </div>
            </div>
            {% for svc in service %}
                <div class="panel panel-primary">
                    <div class="panel-heading">{{ svc.name }}</div>
                    <div class="panel-body">
                        <textarea rows="25" class="form-control" value="">{{ svc.content }}</textarea>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>